name: CD

on:
  push:
    branches:
      - main
  workflow_call:

jobs:
  frontend-ci:
    uses: ./.github/workflows/ci.yml

  frontend-e2e:
    uses: ./.github/workflows/e2e.yml

  frontend-cd:
    needs: [frontend-e2e]
    name: Frontend Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: echo 'Deploy'
